<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="BajaTurno.aspx.cs" Inherits="TPINT_GRUPO_5_PR3.Vistas.Turno.BajaTurno" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Baja Turno</title>
    <link rel="stylesheet" href="../Estilos/Base.css" />
    <link rel="stylesheet" href="../Estilos/NavBar.css" />
    <style>
        #gvTurnos {
            margin: 20px auto;
            display: block;
            border-collapse: collapse;
            margin-top: 10px;
            margin-bottom: 20px;
            width: fit-content;
            text-align: center;
            border-radius: 10px;
            overflow: hidden;
            background-color: #f4f8fb;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.05);
            justify-self: center;
        }

            #gvTurnos th {
                background-color: #1976d2;
                color: white;
                padding: 10px;
                font-weight: 600;
            }

            #gvTurnos td {
                padding: 10px;
                border: 1px solid #e3f2fd;
                cursor: pointer;
                transition: background-color 0.2s ease;
            }

                #gvTurnos td:hover {
                    background-color: #bbdefb;
                }

            #gvTurnos .selected {
                background-color: #1976d2 !important;
                color: white;
                font-weight: bold;
                border-radius: 5px;
            }

            #gvTurnos a {
                background-color: #0078d4;
                color: white;
                padding: 6px 10px;
                border-radius: 6px;
                text-decoration: none;
                font-size: 13px;
                transition: background-color 0.2s ease;
            }

                #gvTurnos a:hover {
                    background-color: #005fa3;
                }

                main .container {
                    display: flex;
                    flex-direction: row;
                    justify-content: space-between;
                    align-content: center;
                    height: fit-content;
                }

                #txtDni{
                    width: 50%;
                    padding: 1rem 1rem !important;
                }

                #btnBuscar{
                    width: 30%;
                }
    </style>
</head>
<body>
    <form id="form1" runat="server" defaultbutton="btnBuscar">
        <nav>
            <div class="leftSide">
                <asp:HyperLink CssClass="hlnk_Inicio" runat="server" Text="Inicio" NavigateUrl="~/Vistas/Inicio.aspx"></asp:HyperLink>
                <asp:HyperLink CssClass="hlnk_Inicio" runat="server" Text="Pacientes" NavigateUrl="~/Vistas/HomePacientes.aspx"></asp:HyperLink>
                <asp:HyperLink CssClass="hlnk_Inicio" runat="server" Text="Medicos" NavigateUrl="~/Vistas/HomeMedicos.aspx"></asp:HyperLink>
            </div>
            <div class="rightSide">
                <asp:Label ID="lblUsuario" CssClass="lbl_Usuario" runat="server" Text="Username"></asp:Label>
                <asp:Button ID="btnLogout" runat="server" Text="Cerrar Sesion" CssClass="btn-logout" OnClick="btnLogout_Click" />
            </div>
        </nav>
        <main>
            <h1>Baja Turno</h1>

            <p>Buscar DNI:</p>
            <div class="container">
                <asp:TextBox ID="txtDni" runat="server" ValidationGroup="2"></asp:TextBox>
                <asp:RegularExpressionValidator ID="revDni" runat="server" ControlToValidate="txtDni" Display="Dynamic" Font-Bold="True" ForeColor="Red" ValidationExpression="^[0-9,$]*$" ValidationGroup="2">* DNI Invalido</asp:RegularExpressionValidator>
                <asp:RequiredFieldValidator ID="rfvDni" runat="server" ControlToValidate="txtDni" Display="Dynamic" Font-Bold="True" ForeColor="Red" ValidationGroup="2">* Requerido</asp:RequiredFieldValidator>
            </div>

            <div class="container">
                <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btnEnviar" OnClick="btnBuscar_Click1" ValidationGroup="2" />
            </div>

            <div class="cotainer">
                <asp:Button ID="btnMostrarTodos" runat="server" Text="Mostrar Todos" CssClass="btnEnviar" OnClick="btnMostrarTodos_Click" />
            </div>

            <div class="container">
                <asp:Label ID="lblConfirmacion" runat="server" Font-Bold="True"></asp:Label>
            </div>

            <asp:GridView ID="gvTurnos" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" EmptyDataText="No se encontraron registros" OnPageIndexChanging="gvTurnos_PageIndexChanging" OnRowDeleting="gvTurnos_RowDeleting" PageSize="5">
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_id" runat="server" Text='<%# Bind("IdTurno_Turno") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Fecha">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_fecha" runat="server" Text='<%# Bind("Fecha") %>' OnDataBinding="lbl_it_fecha_DataBinding"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Legajo Medico">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_legajoMedico" runat="server" Text='<%# Bind("LegajoMedico_Turno") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="DNI Paciente">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_dniPaciente" runat="server" Text='<%# Bind("DNIPaciente_Turno") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Asistencia">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_asistencia" runat="server" Text='<%# Bind("Asistencia_Turno") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Observacion">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_observacion" runat="server" Text='<%# Bind("Observacion_Turno") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>


        </main>
    </form>
</body>
</html>
